#### **PROBLEM 1**

In [1]:
import numpy as np

# Define the matrix
A = np.array([[3, 4], [2, 5]])

# Calculate the determinant
det_A = np.linalg.det(A)

# Check if the matrix is invertible
if det_A != 0:
    # Calculate the inverse
    A_inv = np.linalg.inv(A)
    print("Inverse of A:")
    print(A_inv)
else:
    print("Matrix A is not invertible.")

Inverse of A:
[[ 0.71428571 -0.57142857]
 [-0.28571429  0.42857143]]


#### **PROBLEM 2**

In [2]:
import numpy as np

# Define the coefficient matrix
A = np.array([[2, 3], [4, -1]])

# Define the constant vector
b = np.array([7, 5])

# Check if the matrix is invertible
if np.linalg.det(A) != 0:
    # Solve for x using matrix inverse
    x = np.linalg.inv(A).dot(b)
    print("Solution for [x, y]:")
    print(x)
else:
    print("Matrix A is not invertible, no unique solution.")

Solution for [x, y]:
[1.57142857 1.28571429]


#### **PROBLEM 3**

In [3]:
import numpy as np

# Define the matrix
A = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])

# Calculate the determinant
det_A = np.linalg.det(A)

# Check if the matrix is invertible
if det_A != 0:
    # Calculate the inverse
    A_inv = np.linalg.inv(A)
    print("Inverse of A:")
    print(A_inv)
else:
    print("Matrix A is not invertible.")

Inverse of A:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


#### **PROBLEM 4**

In [4]:
import numpy as np

# Define the coefficient matrix
A = np.array([[1, 1, 1], [2, 5, 1], [2, 3, 8]])

# Define the constant vector
b = np.array([6, -4, 9])

# Check if the matrix is invertible
if np.linalg.det(A) != 0:
    # Solve for x using matrix inverse
    x = np.linalg.inv(A).dot(b)
    print("Solution for [x, y, z]:")
    print(x)
else:
    print("Matrix A is not invertible, no unique solution.")

Solution for [x, y, z]:
[10.84210526 -5.21052632  0.36842105]


#### **`PROBLEM 5`**

In [5]:
import numpy as np

# Define the coefficient matrix
A = np.array([[4, -1, 0], [3, 5, 2], [-2, 4, 1]])

# Define the constant vector
b = np.array([5, 6, 2])

# Check if the matrix is invertible
if np.linalg.det(A) != 0:
    # Solve for x using matrix inverse
    x = np.linalg.inv(A).dot(b)
    print("Solution for [x, y, z]:")
    print(x)
else:
    print("Matrix A is not invertible, no unique solution.")

Solution for [x, y, z]:
[  2.6   5.4 -14.4]


#### **BONUS CHALLENGE**

In [6]:
import numpy as np

def matrix_inverse(A):
    """
    Calculates the inverse of a matrix if it exists.

    Args:
        A: A square numpy array representing the matrix.

    Returns:
        The inverse of the matrix if it exists, otherwise prints a message.
    """

    det_A = np.linalg.det(A)
    if det_A != 0:
        return np.linalg.inv(A)
    else:
        print("Matrix A is not invertible.")

# Example usage
A = np.array([[2, 1], [4, 3]])
inverse_A = matrix_inverse(A)
if inverse_A is not None:
    print("Inverse of A:")
    print(inverse_A)

Inverse of A:
[[ 1.5 -0.5]
 [-2.   1. ]]
